### ISSUE TITLE
Naive pub/sub example should be in ros2 directory

### ISSUE THREAD

**Issue by griswaldbrooks** [PickNikRobotics/ros_testing_templates#6]
### Need

_In order to_ see a naive example of pub/sub testing in ros2
_As a_ developer
_I want to_ have a naive pub/sub package

### Acceptance Criteria

**Scenario:** ros2 pub/sub node should exist for testing
**GIVEN** we want to show testing pub/sub in ros2
**WHEN** writing those gtests
**THEN** a naive publisher/subscriber package should be available

### Tasks
- [ ] Create ros2 `naive` package
- [ ] Port `Incrementer` class into package
- [ ] Write readme on how to use on cli

### Notes

References:
https://github.com/PickNikRobotics/ros_testing_templates/tree/main/ros1/naive
